'use strict';

/**
 * Canonical seed for build3's startup perks ("Perks & credits") - SaaS credits,
 * discounts, coworking, and hiring benefits build3 has negotiated for its founders,
 * transcribed from the internal "SaaS tools / benefits" sheet. This is both the input
 * to scripts/seed_perks.js and the fallback the domain layer uses when the Supabase
 * `perks` table is absent or empty. Once seeded and editable from /admin, the table is
 * the source of truth. Mirrors mentors.data.js.
 *
 * how_to_access is kept verbatim (the actionable part - links, emails, steps); a few
 * entries whose source text said "apply using this link/here" with the URL only as a
 * cell hyperlink have that real recovered link appended so the card is actionable.
 * access_url is the primary link (null for email-only or link-less entries).
 */

const PERKS = [
  {
    slug: 'away-center',
    name: 'away.center',
    objective: 'Premium coworking, meeting rooms, and workspace access for founders',
    categories: ['workspace'],
    description: 'away.center gives build3 members access to calm, design led workspaces across Bengaluru, Kolkata, and Vizag. The spaces are suitable for founder workdays, team sprints, investor meetings, client calls, workshops, and community gatherings. \n\nbuild3 member benefits: \n• First day pass free for new visitors, subject to availability \n• 20% discount on day passes \n• 15% discount on meeting room bookings \n• 10% discount on monthly coworking plans \n• Custom pricing for build3 workshops, founder meetups, and small community events',
    how_to_access: 'Email hello@away.center with your name, startup name, city, preferred away location, date of visit, and requirement. Please mention build3 member in the subject or body of the email. The away team will confirm availability and share the next steps.\n\nhttps://www.away.center/koramangala-free-day',
    access_url: 'https://www.away.center/koramangala-free-day',
    sort_order: 1,
  },
  {
    slug: 'aws-activate',
    name: 'AWS Activate',
    objective: 'On-demand cloud computing',
    categories: ['cloud'],
    description: 'AWS Activate Program: AWS Activate is a free program designed for startups and early-stage entrepreneurs that provides AWS credits wirth $1,000.\n\nEligibility:\n• New to AWS Activate credits\n• Self-funded or pre-Series B (most recent funding round must be within the last 12 months, if applicable)\n• Have a fully-functioning company website\n• Founded in the past 10 years\n\nDetailed FAQs',
    how_to_access: '1. Apply using this link\n\n2. Fill in all the necessary details\n\n3. Instead of filling an Activate Provider code go for Activate Founders program\n\n4. Once eligibility is verified, your account will be credited with $1,000 worth of AWS credits\n\nhttps://aws.amazon.com/startups/credits',
    access_url: 'https://aws.amazon.com/startups/credits',
    sort_order: 2,
  },
  {
    slug: 'canva',
    name: 'Canva',
    objective: 'Designing creative assets with collaboration',
    categories: ['design'],
    description: 'Canva makes designing beautiful creative assets easy for everyone. You can use it to design social media images, videos and gifs to posters, websites, booklets, multimedia presentations, and heaps more.',
    how_to_access: 'In order to activate Canva for you, please email studio@build3.org (CC: ckj@build3.org), with email ids and duration for which access to Canva is required. The same will be activated in 48 working hours and you will receive the login details via email.',
    access_url: null,
    sort_order: 3,
  },
  {
    slug: 'notion',
    name: 'Notion',
    objective: 'Task management and project tracking',
    categories: ['productivity'],
    description: 'Task management and project tracking',
    how_to_access: 'To redeem 6 months free of Notion Business with Notion AI included, please submit your application at: https://ntn.so/build3\n\nEligibility requirements of the offer\n1. Meets terms and conditions\n2. Must be a new, non-paying Notion customer\n3. Under 100 employees',
    access_url: 'https://ntn.so/build3',
    sort_order: 4,
  },
  {
    slug: 'zendesk',
    name: 'Zendesk',
    objective: 'SaaS tools for customer sales and support',
    categories: ['sales'],
    description: 'Zendesk is a service-first CRM company with support, sales, and customer engagement products designed to improve customer relationships. build3 companies get six months of free access to Zendesk Suite and Zendesk Sales CRM. This offer is only available for build3 startups that are new customers with fewer than 100 employees and funding no greater than Series B.\n\nStartup Program Benefits:\nSix months of access to our Zendesk Suite and Zendesk Sales CRM at no cost\nOnline office hour sessions with our startups customer success team\nAccess to our Startups Community including events, content and resources\n\nRequirements:\nNew Zendesk customer\nUnder 100 employees\nStartup with funding no greater than Series B',
    how_to_access: 'Startups can apply here: https://www.zendesk.com/campaign/partner-startups/?partner_account=0016R00003GS8LxQAL',
    access_url: 'https://www.zendesk.com/campaign/partner-startups/?partner_account=0016R00003GS8LxQAL',
    sort_order: 5,
  },
  {
    slug: 'zoho',
    name: 'Zoho',
    objective: 'Business software solutions ecosystem',
    categories: ['cloud', 'productivity'],
    description: 'More than 45 software application to manage, connect, and automate business processes across your organization. Please visit www.zoho.com to know more. All eligible startups registered with Zoho partners (including build3) can avail 1 lakh INR worth credits. And those who are interested in hosting their email with Zoho can get an additional 86K INR worth of credits to explore Zoho Mail and related services.',
    how_to_access: 'https://www.zoho.com/startups/founders-registration.html \n\ngo to this link and in the question startup ecosystem enabler - tick yes, and select build3',
    access_url: 'https://www.zoho.com/startups/founders-registration.html',
    sort_order: 6,
  },
  {
    slug: 'supermorpheus',
    name: 'Supermorpheus',
    objective: 'Bouquet of services',
    categories: ['cloud'],
    description: 'Supermorpheus Partnerships are for:\nCredits and discounts for popularly used services like Google Cloud, AWS, etc.\nExclusive offers and discounts by startups that are part of the SM community',
    how_to_access: 'Here is where you can access the: Supermorpheus Partnerships page- https://supermorpheus.notion.site/be948e52c6c143c790034ff359a93476?v=e8bd8a3f58e2440daed8263f645796df \n\nSteps to access each tool are within the individual pages.',
    access_url: 'https://supermorpheus.notion.site/be948e52c6c143c790034ff359a93476?v=e8bd8a3f58e2440daed8263f645796df',
    sort_order: 7,
  },
  {
    slug: 'msg91',
    name: 'MSG91',
    objective: 'Automating customer interactions',
    categories: ['marketing'],
    description: 'MSG91 is a Cloud communications platform that provides secure and robust APIs for SMS, Email, WhatsApp, Voice, Authentication and more. MSG91\'s startup program offers 6 months of free credits that can be availed in either of the following ways: \n*25,000 SMS credits per month for 6 months.\n*400,000 Emails and 4,000 Email Verifications per month for 6 months.\n*8,500 WhatsApp Sessions per month along with WhatsApp Chatbot for 6 months.\n*25,000 OTP verification SMS credits per month for 6 months.\n*Voice, IVR Calling and Virtual Number credits worth INR 6250 per month for 6 months.\n*Free access to Cloud Contact Center/Ticket Management Platform HELLO, Data Management & Warehouse Application SEGMENTO, Flow Automation Application CAMPAIGN, MSG91’s FAQ software KnowledgeBase.',
    how_to_access: '1. Fill the application form: https://msg91.com/startups-form \n2. Sign up into MSG91 using the link: https://msg91.com/signup?utm_source=build3\n3. Use your trial account. After the trial credits are utilized, the 6 months\' free credits will be added to the account by MSG91.',
    access_url: 'https://msg91.com/startups-form',
    sort_order: 8,
  },
  {
    slug: 'build3-freshteam',
    name: 'build3 freshteam portal',
    objective: 'To source candidates for hiring',
    categories: ['hiring'],
    description: 'build3\'s job portal gets a significant number of hits every month. Previously, founders have listed their job postings on our page, and found it useful to generate/grow their hiring pipeline.',
    how_to_access: 'Email studio@build3.org with the job posting details - job title, location, description, etc.',
    access_url: null,
    sort_order: 9,
  },
  {
    slug: 'microsoft-for-startups',
    name: 'Microsoft for Startups',
    objective: 'Cloud computing and tons of extra add on services',
    categories: ['cloud'],
    description: 'Microsoft for Startups Hub: Microsoft for Startups Hub is a comprehensive program aimed at fostering innovation and growth in startups by providing tools, resources, and expert support necessary to build and scale their businesses using Microsoft technologies.\n\nMicrosoft for Startups Hub Benefits:\n1. Azure Credits: Qualify for up to $120,000 in Azure credits over 2 years to power your business operations and reduce initial cloud hosting costs.\n2. Technical Support: Gain access to Microsoft engineers for architectural guidance and troubleshooting to help optimize your technology stack.\n3. Microsoft 365: Receive licenses for Microsoft 365, allowing your team to use Microsoft’s productivity tools.\n4. Go-to-Market Support: Leverage customized marketing and sales opportunities to reach new customers and expand your market presence.\n5. Exclusive Offers: 30+ additional free and discounted tools, tech, and services from Microsoft and our partners including M365, GitHub, LinkedIn, and more.\n6. Free access to leading AI models through Azure, including OpenAI GPT-4, Llama 2 from Meta, and more. Get up to $150,000 in Azure credits, plus $2,500 of OpenAI credits.\n\nEligibility:\n• Microsoft for Startups Founders Hub is open to anyone – from students with an idea to serial founders. However, to be eligible for the program, your startup must be:\n• Building a software based product or service\n• Privately held and for-profit\n• Have not received Series D or later funding\n• Have not previously received more than $10,000 in Azure credits\n\nDetailed criterion',
    how_to_access: '1. Have a LinkedIn account ready (you apply with it).\n2. Go to the Microsoft for Startups Founders Hub and click Sign Up.\n3. Click "Apply with LinkedIn", fill in your startup details, and upload any supporting docs (pitch deck / proof of incorporation).\n4. Submit. You will get an email acknowledgement, and Microsoft reviews it before granting access.',
    access_url: null,
    sort_order: 10,
  },
  {
    slug: 'webflow',
    name: 'Webflow',
    objective: 'Website design and hosting platform',
    categories: ['design'],
    description: 'build3 is a Webflow startup program partner. Through this partnership, eligible startups incubated at build3 can receive 12 months of free access to a Webflow CMS site plan.\n\nEligibility Requirements:\n\n1. Must have less than 50 employees\n2. Must have raised less than $15M in funding\n3. Must not be a current Webflow customer',
    how_to_access: '1. Visit Webflow\'s startup application portal here\n\n2. Click on Apply for the startup discount button\n\n3. Fill all the necessary details as required by Webflow on the form\n\n4. During the application process, select "Build3" as your VC partner you\'re working with\n\n5. Complete the application to redeem your 12-month free CMS site plan\n\nhttps://webflow.com/startups',
    access_url: 'https://webflow.com/startups',
    sort_order: 11,
  },
  {
    slug: 'creatosaurus',
    name: 'Creatosaurus',
    objective: 'Content creation & social media marketing tool powered by AI',
    categories: ['design', 'marketing'],
    description: 'Creatosaurus is your all in one content creation & social media marketing tool powered by AI. It combines a graphic design editor, document editor, generative AI toolkit, video editor, social media scheduler, content calendar, social inbox, social analytics, SEO keywords, automations, 20+ 3rd party apps, and more—all in one place.\n\nWebsite - https://www.creatosaurus.io',
    how_to_access: '1. Visit https://www.creatosaurus.io/pricing\n2. Select any plan & click upgrade\n3. Add coupon code “BUILD6“ or “BUILD50“ in the checkout. Proceed & done!\n\n "BUILD6" - Free 6 Months Creatosaurus Teams Plan, saving more than $500.\n"BUILD50" - 50% OFF on any annual plan\n\nor email us at malav@creatosaurus.io',
    access_url: 'https://www.creatosaurus.io/pricing',
    sort_order: 12,
  },
  {
    slug: 'groweasy',
    name: 'GrowEasy',
    objective: 'Performance Marketing Automation Software',
    categories: ['marketing'],
    description: 'GrowEasy.ai is AI powered platform which will act as entire marketing team, will do end to end content, graphics, keyword targeting for your paid campaigns.\n\nIt is easiest way to do paid marketing for your business.',
    how_to_access: 'Tej, founder of GrowEasy has opened up his calendar to give personalised demos and free one on one consultation for framing your marketing strategy \n\n\nLink to Tej\'s calendar\n\nhttps://calendar.app.google/vVRqXCAniCcqfBFb7',
    access_url: 'https://calendar.app.google/vVRqXCAniCcqfBFb7',
    sort_order: 13,
  },
  {
    slug: 'perplexity',
    name: 'Perplexity',
    objective: 'Embedding AI witin products',
    categories: ['ai'],
    description: 'Perplexity is offering Build3 startups access to their AI-powered search API + core product to help founders build amazing products. Each Build3-backed startup will get $5K in Sonar API credits and 6 months for Enterprise Pro for free (up to 50 seats)',
    how_to_access: '1. Apply here : https://www.perplexity.ai/startups \n\n2. Select "Build3" as the Startup Partner \n\n3. Follow the email to get set up',
    access_url: 'https://www.perplexity.ai/startups',
    sort_order: 14,
  },
  {
    slug: '91springboard',
    name: '91springboard',
    objective: 'Virtual Office Services',
    categories: ['workspace'],
    description: '91sprinboard is offering discounted rates to build3 portfolio services for company incorporation, Goods and Services Tax (GST) registration, Shops & Establishment, correspondence/mail handling.',
    how_to_access: '1. Send an email to studio@build3.org sharing the official company name, founder/POC Name and Contact details.\n\n2. Follow the email to get set up',
    access_url: null,
    sort_order: 15,
  },
  {
    slug: 'cashfree',
    name: 'Cashfree Payments',
    objective: 'Payment Gateway',
    categories: ['sales'],
    description: 'Cashfree Payments has partnered with build3 to provide favorable merchant rates and a dedicated account executive for avaialing the payment gateway',
    how_to_access: 'Use the following link to get access to the gateway : https://merchant.cashfree.com/merchants/signup?referrer=partner&refCode=CFPB3953099',
    access_url: 'https://merchant.cashfree.com/merchants/signup?referrer=partner&refCode=CFPB3953099',
    sort_order: 16,
  },
  {
    slug: 'future-agi',
    name: 'Future AGI',
    objective: 'Autonomous AI agent infrastructure',
    categories: ['ai'],
    description: 'Future AGI Can help you with :- \n1. Rapidly iterate and deploy reliable AI products with confidence - Future AGI\'s platform reduces AI product development time by up to 95% through automated optimization and no-code experimentation capabilities.\n2. Validate performance and user trust at every stage of development - The platform provides comprehensive evaluation metrics including context relevance, factual accuracy, and built-in safety evaluations to ensure AI outputs meet quality standards throughout the development lifecycle.\n3. Save Engineering bandwidth to focus more on product development instead of debugging - Future AGI\'s developer-first integration seamlessly connects with industry-standard tools, eliminating the need to manage separate tools for testing, monitoring, and optimization.\n\n\nFuture AGI’s Startup Catalyst program offers \n* $5,000 in Platform Credits\n* 6 Months Pro Plan Access\n* Complete Technical Support',
    how_to_access: '1. Apply at futureagi.com/startups\nnote :- Make sure while applying write Your startup name as "build3_startup name"',
    access_url: 'https://futureagi.com/startups',
    sort_order: 17,
  },
  {
    slug: 'atlassian',
    name: 'Atlassian',
    objective: 'Project Management',
    categories: ['productivity'],
    description: 'Supercharged by Al, work smarter every step of the way with tools designed to plan, track, and collaborate on work from MVP to IPO.\n\n1. Streamline product development – Use Jira to plan sprints, track bugs, and ship features faster with complete visibility across your engineering team.\n\n2. Centralize team knowledge – Keep product specs, meeting notes, and documentation in Confluence so everyone stays aligned without endless meetings.\n\n3. Scale collaboration effortlessly – Connect development, design, and business teams with Trello boards, Bitbucket repos, and automated workflows that grow with you.\n\nAtlassian\'s Startup program offers \n* 12M 50 seats of all premium Atlassian products',
    how_to_access: '1. Apply at https://www.atlassian.com/software/startups?utm_source=&utm_medium=comarketing&utm_campaign=P:atlassian|O:|I:a4s-vc-build3|',
    access_url: 'https://www.atlassian.com/software/startups?utm_source=&utm_medium=comarketing&utm_campaign=P:atlassian|O:|I:a4s-vc-build3|',
    sort_order: 18,
  },
  {
    slug: 'github',
    name: 'GitHub',
    objective: 'Code Management',
    categories: ['productivity'],
    description: 'GitHub can help you with:\n\n1. Build and scale with enterprise-grade tools for free – Get up to 20 seats of GitHub Enterprise free for one year, including advanced security, CI/CD, and private repositories .\n2. Accelerate development with AI-powered collaboration – Use GitHub Copilot, automated workflows, and project boards to help your team ship code faster and smarter .\n3. Secure your code from day one – Protect your startup with built-in security features like code scanning, secret protection, and dependency alerts—without needing separate tools .\n\nGitHub\'s Startup program offers \n* 20 seats of GitHub Enterprise free for year 1 and 50% off 20 seats for year 2(plus lots of resources to help ensure they get the most out of their credits).',
    how_to_access: '1. Apply at https://resources.github.com/startups/?pid=build3',
    access_url: 'https://resources.github.com/startups/?pid=build3',
    sort_order: 19,
  },
  {
    slug: 'tally',
    name: 'Tally.so',
    objective: 'Forms',
    categories: ['productivity'],
    description: 'Tally is a simple, yet powerful form builder that allows you to create any type of form without breaking the bank. Creators and teams use Tally to kickstart their business, validate ideas, gather customer feedback, perform market research or sell products.\nWorks like a doc: Just start typing and use shortcuts to create any type of form in seconds.\nUnlimited forms & responses for free: Tally is the only form builder out there that offers unlimited forms, responses and advanced features for free.\nTally Pro: 99% of the features are available for free, combined with an empowering Pro plan aimed at the needs of creators & teams such as team collaboration, custom domains, removal of Tally branding, and more.',
    how_to_access: 'How to apply?\n1. Startups can apply here\n2. They need to choose \'build3\' from the dropdown list\n3. And use the partner code: build30306\n4. They will receive an email from us with the discount code\n\nGood to know\nThe 50% discount code applies to the monthly or yearly plan (for 12 months).\nThe discount is only valid for new, first-time paying Tally Pro users\nThe discount code is only valid for startups in your network (not to share publicly).\n\nhttps://tally.so/help/tally-for-startups',
    access_url: 'https://tally.so/help/tally-for-startups',
    sort_order: 20,
  },
];

module.exports = { PERKS };
